defaults:
  - process: process1
  - model: model1
  - _self_

raw: 
  path: data/raw/Social_Network_Ads.csv

processed:
  dir: data/processed
  target: 
    name: target.csv
    path: ${processed.dir}/${processed.target.name}
  features:
    name: features.csv
    path: ${processed.dir}/${processed.features.name}

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

map_columns:
  Gender[Female]: gender-female
  Gender[Male]: gender-male