name: Add Colab Badge
on: [push]

jobs:
  badges:
    name: Example Badge Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v2

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v4
        with:
          check: "all"
          target_branch: master
          target_repository: khuyentran1401/employee-future-prediciton
          update: true
      
      - name: Add, commit, and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Add Colab badge
          push: true
