name: Run tests
on: [push, pull_request]

jobs:
  checkout:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: Poetry setup
        uses: ClementWalter/poetry-action@v1
        with:
          os: ubuntu-latest
          python-version: 3.8

      - name: Run tests
        run: pytest tests