name: Run tests
on: [push, pull_request]

jobs:
  checkout:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v1
        
      - name: Poetry setup
        uses: knowsuchagency/poetry-install@v1
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Run tests
        run: pytest tests