name: Run tests
on: [push]
jobs:
  checkout:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
        
      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run training tests
        run: pytest training/tests

      - name: Serve the app locally and run app tests
        run: |
          bentoml serve ./application/src/create_service.py:service  & 
          sleep 2
          pytest application/tests
          kill -9 `lsof -i:3000 -t`