name: Run tests
on: [push, pull_request]

jobs:
  checkout:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: install
        run: pip install pytest

      - name: Run tests
        run: pytest tests