name: Run tests
on: [push]
jobs:
  checkout:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run training tests
        run: pytest training/tests

      - name: Serve the app locally
        run: bentoml serve training/src/create_service.py:service --reload 

      - name: Run app tests
        run: pytest application/tests