name: Train ML Model
on: [push]

jobs:
  train_ml:
    runs-on: ubuntu-latest
    name: A job to train new model
    steps:
    - name: Checkout 
      id: checkout
      uses: actions/checkout@v2

    - name: Train new model
      id: train
      uses: ZoranPandovski/automl-actions@v1.0.0
      with:
        dataset: "data/raw/Employee.csv"
        target: "LeaveOrNot"
        when: "{City: Bangalore, Gender: Male, EverBenched: Yes, PaymentTier: 1, Age: 20, ExperienceInCurrentDomain: 2}"

    - name: Add, commit, and push changes
      uses: EndBug/add-and-commit@v9
      with:
        message: Add model prediction
        push: true